AllCops:
  Exclude:
    - ".rubocop.yml"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "Gemfile.lock"
    - "Rakefile"
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 99
  Exclude:
    - spec/**/*.rb

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
  Exclude:
    - spec/**/*.rb
